### ISSUE TITLE
【New Data Request】 NFT API

### ISSUE THREAD

**Issue by momohuri** [theta-data/theta-data-api#15]
# What specific data information do you need? Please describe.
It would be great to have this API on theta, to get all NFTs for a wallet: https://github.com/nft-api/nft-api#getnfts

# Why do you need the data
To easily search and displays NFTs on thetaboard.io

**Comment by larryro** [comment]
# Evaluation Notes
we can use this  rpc interface to interact with guardian node to get the smart contract information.
```bash
 curl -X POST -H 'Content-Type: application/json' --data '{"jsonrpc":"2.0","method":"theta.CallSmartContract","params":[{"sctx_bytes":"07f863da9467aa74fb571c382f3ef455d8ba77e687d9fe8f28c280800180d89467aa74fb571c382f3ef455d8ba77e687d9fe8f28c28080831e848085e8d4a51000a4a2f7b3a50000000000000000000000000000000000000000000000000000000000000016"}],"id":1}' http://localhost:16888/rpc
```
**Response**
```json
{"jsonrpc":"2.0","id":1,"result":{"vm_return":"0000000000000000000000004aaa915f23f581e85e5c03c4514eac91aa05ce35000000000000000000000000718ed825af070b41e51aa26e38eeb985e472faa60000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000000000004d747970655f6832666261686d31356478306e657635786270697473736664396e2e6a736f6e3f6e66745f69643d6e66745f7976786830377069666d6d35616e357962353376376663333574716800000000000000000000000000000000000000","contract_address":"0x67aa74fb571c382f3ef455d8ba77e687d9fe8f28","gas_used":"24694","vm_error":""}}
```


**Reference links:**  [https://explorer.thetatoken.org/account/0x67aa74fb571c382f3ef455d8ba77e687d9fe8f28](https://explorer.thetatoken.org/account/0x67aa74fb571c382f3ef455d8ba77e687d9fe8f28)


**Reference Result**

![image](https://user-images.githubusercontent.com/5787117/149616255-2d585172-a737-4da8-bd1e-c43514f88e2b.png)

## To be confirmed
* how to get all the nft smart contract
* How do we record the user's nft holdings data, should we monitor each transaction to calculate the user's nft holdings through nft transaction records or directly through the contract's function interface?
* If the calculation is done by monitoring the transaction records, it is necessary to distinguish which are nft 721 contract posting transactions, which are mint transactions, and which are nft transfer transactions

**Comment by larryro** [comment]
![nft_process](https://user-images.githubusercontent.com/5787117/153010706-120c30de-82c9-457e-afd9-b17ae7a421a0.jpg)

**Comment by larryro** [comment]
> # What specific data information do you need? Please describe.
> It would be great to have this API on theta, to get all NFTs for a wallet: https://github.com/nft-api/nft-api#getnfts
> 
> # Why do you need the data
> To easily search and displays NFTs on thetaboard.io
Relevant data has been provided
**Example**
`{
  Nfts {
    SearchNfts(name: "pineapple") {
      totalCount
      hasNextPage
      nodes {
        name
        call_times
        contract_address
      }
    }
    NftOwners(smart_contract_address: "0x67aa74fb571c382f3ef455d8ba77e687d9fe8f28") {
      endCursor
      hasNextPage
      nodes {
        from
        owner
        name
        img_uri
        token_id
      }
    }
    Balance(wallet_address: "0x685f5251bc8373cf622db841f94caf1b9ef68126") {
      nodes {
        from
        img_uri
        name
      }
      endCursor
      hasNextPage
      totalCount
    }
  }
}`
